apiVersion: v1
kind: Service
metadata:
  name: argocd-notifications
  labels:
    app: argocd-notifications
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: argocd-notifications
